/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Barrier(props) {
  const { nodes, materials } = useGLTF('./models/Barrier.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Barrier} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.Stone} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Barrier}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials.Stone}
      />
    </group>
  )
}

useGLTF.preload('./models/Barrier.glb')