/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Fence(props) {
  const { nodes, materials } = useGLTF('./models/fenceOne.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube313.geometry}
        material={materials['fence metal.003']}
        position={[-20.826, 3.631, 9.721]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube314.geometry}
        material={materials['fence metal.003']}
        position={[6.049, 3.631, 9.721]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube315.geometry}
        material={materials['fence metal.003']}
        position={[-18.279, 3.631, -15.647]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube318.geometry}
        material={materials['fence metal.003']}
        position={[4.728, 1.644, -15.721]}
        rotation={[0, 0, -Math.PI]}
        scale={-1}
      />
    </group>
  )
}

useGLTF.preload('./models/fenceOne.glb')





