/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Frames2(props) {
  const { nodes, materials } = useGLTF('./models/frames2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_5set_OBJ.geometry}
        material={materials.wire_087225143}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.368}
      />
    </group>
  )
}

useGLTF.preload('./models/frames2.glb')
