/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Headphones2(props) {
  const { nodes, materials } = useGLTF('./models/headphones2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['uploads-files-4630106-headphone+8'].geometry}
        material={materials.initialShadingGroup}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('./models/headphones2.glb')
