/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mobile2(props) {
  const { nodes, materials } = useGLTF('./models/mobile2.glb')
  return (
    <group {...props} dispose={null} scale={[10,10,10]} position={[-20,5.6,-20]} rotation-x={Math.PI*-0.1}>
      <group position={[0, 0.074, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.Display}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Body}
          position={[0.019, -0.005, -0.065]}
          scale={[1.314, 1, 1.199]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials['Glass.001']}
            position={[0, -0.001, 0]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials.camara}
          position={[-0.011, 0.003, -0.07]}
          scale={-0.002}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials['Glass.001']}
            position={[0, -0.585, -0.003]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.camara}
          position={[0.023, -0.005, -0.065]}
          scale={[0.002, 0, 0.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.camara}
          position={[0.015, -0.005, -0.065]}
          scale={[0.002, 0, 0.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MI_Logo.geometry}
          material={materials['MI Logo']}
          position={[0, -0.004, 0.048]}
          rotation={[0, 0, -Math.PI]}
          scale={0.01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/mobile2.glb')
