/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mobile4(props) {
  const { nodes, materials } = useGLTF('./models/mobile4.glb')
  return (
    <group {...props} dispose={null} scale={[35,35,35]}  position={[-32.45,5.3,-19.8]} rotation-y={Math.PI*2.6} rotation-z={Math.PI*-0.1}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Buttons007_Cube044.geometry}
        material={materials['Screen_material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Buttons008_Cube045.geometry}
        material={materials['Screen_material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Buttons_Cube046.geometry}
        material={materials['Screen_material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera001_camera_1.geometry}
          material={materials.gray_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera001_camera_2.geometry}
          material={materials.Black_glass}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera002_camera001_1.geometry}
          material={materials.gray_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera002_camera001_2.geometry}
          material={materials.Black_glass}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera003_camera002_1.geometry}
          material={materials.gray_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera003_camera002_2.geometry}
          material={materials.Black_glass}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera004_camera003_1.geometry}
          material={materials.gray_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera004_camera003_2.geometry}
          material={materials.Black_glass}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera_camera004_1.geometry}
          material={materials.gray_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera_camera004_2.geometry}
          material={materials.Black_glass}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_Cube047_1.geometry}
          material={materials['phone_material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_Cube047_2.geometry}
          material={materials.material_port}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flashlight001_Circle017.geometry}
        material={materials.flashlight}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.frame001_Circle019.geometry}
        material={materials['Screen_material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame003_Frame001.geometry}
        material={materials['Screen_material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Inscriptions_Mesh.geometry}
        material={materials.glass}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.phone002_1.geometry}
          material={materials.phone_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.phone002_2.geometry}
          material={materials['phone_material.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.scanner002_Cube043.geometry}
        material={materials.glass_}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen002_Plane003_1.geometry}
          material={materials['Screen_material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen002_Plane003_2.geometry}
          material={materials['Screen_material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen002_Plane003_3.geometry}
          material={materials['Screen_material.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/mobile4.glb')
