/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mobile(props) {
  const { nodes, materials } = useGLTF('./models/mobile.glb')
  return (
    <group {...props} dispose={null} scale={[10,10,10]} position={[-15,6.4,-20.3]} rotation-z={Math.PI / 2}  rotation-x={Math.PI*-1.1} rotation-y={Math.PI *1.5}> 
      <group scale={[0.039, 0.042, 0.039]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.phone} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.black_bit}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials.screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_3.geometry}
          material={materials.lens}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/mobile.glb')
