/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PhoneBox(props) {
  const { nodes, materials } = useGLTF('/phoneBox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FrontBox.geometry}
        material={materials.Box}
        position={[0.053, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/phoneBox.glb')
