/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PhoneBox3(props) {
  const { nodes, materials } = useGLTF('./models/phoneBox3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Box-Top']}
      />
    </group>
  )
}

useGLTF.preload('./models/phoneBox3.glb')
