/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PSConsole2(props) {
  const { nodes, materials } = useGLTF('./models/PSconsole.glb')
  return (
    <group {...props} dispose={null} scale={[1.5,1.5,1.5]} position={[-16,5,16]} rotation={[0,Math.PI,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PS4_Base.geometry}
        material={materials.Material}
      />
      <group position={[0, 0.113, -0.042]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PS4_Controller.geometry}
        material={materials.joystick}
        position={[0.332, 0.088, 0.944]}
        rotation={[0.536, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('./models/PSconsole.glb')