/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shelf(props) {
  const { nodes, materials } = useGLTF('./models/shelf.glb')
  return (
    <group {...props} dispose={null} rotation={[0,Math.PI,0]} position={[-29,1.5,48.5]} scale={[2.5,2.5,2.5]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['polished white']}
        position={[3.323, 0, 0]}
        scale={2.319}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.014']}
        position={[2.86, 2.837, -0.263]}
        rotation={[1.553, -0.175, -0.003]}
        scale={0.018}
      />
      <group
        position={[2.561, 3.051, -0.261]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.007, 0.008, 0.007]}>
        <mesh
          name="Plane002_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials['Material.010']}
          morphTargetDictionary={nodes.Plane002_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane002_1.morphTargetInfluences}
        />
        <mesh
          name="Plane002_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials['Material.009']}
          morphTargetDictionary={nodes.Plane002_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane002_2.morphTargetInfluences}
        />
        <mesh
          name="Plane002_3"
          castShadow
          receiveShadow
          geometry={nodes.Plane002_3.geometry}
          material={materials['Material.012']}
          morphTargetDictionary={nodes.Plane002_3.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane002_3.morphTargetInfluences}
        />
      </group>
      <group
        position={[2.909, 2.634, -0.259]}
        rotation={[1.722, 0.121, -0.456]}
        scale={[0.031, 0.022, 0.064]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials['BRAKE_Disk.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_3.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_4.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_5.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_6.geometry}
          material={materials['Material.006']}
        />
      </group>
      <group
        position={[2.887, 2.695, -0.297]}
        rotation={[1.722, 0.121, -0.456]}
        scale={[0.031, 0.022, 0.064]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials['BRAKE_Disk.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_3.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_4.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_5.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_6.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_7.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Material.002']}
        position={[2.769, 2.893, -0.263]}
        rotation={[-3.122, -0.004, 1.337]}
        scale={0.035}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['Material.003']}
        position={[2.763, 2.94, -0.303]}
        rotation={[1.101, -0.514, -0.523]}
        scale={0.022}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Material.005']}
        position={[2.86, 3.013, -0.275]}
        rotation={[0.488, 0.164, 0.037]}
        scale={0.014}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
        position={[2.822, 2.997, -0.317]}
        rotation={[1.614, 0, 0]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001.geometry}
        material={materials['Material.007']}
        position={[2.783, 2.913, -0.308]}
        rotation={[-0.397, 0.474, 1.833]}
        scale={0.026}
      />
      <group position={[2.821, 2.882, -0.23]} scale={[0.112, 0.111, 0.085]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody001.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody001_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody001_2.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group position={[2.767, 2.959, -0.336]} rotation={[1.742, -0.017, 3.136]} scale={0.088}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody004.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody004_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody004_2.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group position={[2.821, 2.882, -0.23]} scale={[0.112, 0.111, 0.085]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody003.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody003_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody003_2.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group position={[2.888, 2.937, -0.225]} rotation={[-0.073, 0.161, 0.563]} scale={0.088}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody002.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody002_1.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody002_2.geometry}
          material={materials['Carlight triangle chrome white']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody002_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sBody002_4.geometry}
          material={materials['Material.005']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MainBody001.geometry}
        material={materials['Material.003']}
        position={[2.888, 2.937, -0.225]}
        rotation={[-0.073, 0.161, 0.563]}
        scale={0.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.006']}
        position={[2.883, 2.982, -0.288]}
        rotation={[0, 0, -1.234]}
        scale={[0.027, 0.021, 0.027]}
      />
      <group position={[2.821, 2.985, -0.262]} scale={[0.011, 0.017, 0.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube065.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube065_1.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube065_2.geometry}
          material={materials['Material.014']}
        />
      </group>
      <group
        position={[2.884, 2.639, -0.27]}
        rotation={[0, 0, -0.002]}
        scale={[0.007, 0.008, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_3.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_4.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[2.884, 2.639, -0.27]}
        rotation={[0, 0, -0.002]}
        scale={[0.007, 0.008, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
      </group>
      <group
        position={[2.929, 2.995, -0.292]}
        rotation={[1.154, -1.421, 1.147]}
        scale={[0.025, 0.029, 0.026]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_3.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_4.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_5.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group
        position={[2.937, 2.92, -0.296]}
        rotation={[Math.PI, 0, -0.041]}
        scale={[-0.03, -0.03, -0.021]}>
        <mesh
          name="Cube058_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_1.geometry}
          material={materials['Material.003']}
          morphTargetDictionary={nodes.Cube058_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube058_1.morphTargetInfluences}
        />
        <mesh
          name="Cube058_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_2.geometry}
          material={materials['BRAKE_Disk.002']}
          morphTargetDictionary={nodes.Cube058_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube058_2.morphTargetInfluences}
        />
        <mesh
          name="Cube058_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_3.geometry}
          material={materials['Material.006']}
          morphTargetDictionary={nodes.Cube058_3.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube058_3.morphTargetInfluences}
        />
        <mesh
          name="Cube058_4"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_4.geometry}
          material={materials['Material.008']}
          morphTargetDictionary={nodes.Cube058_4.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube058_4.morphTargetInfluences}
        />
        <mesh
          name="Cube058_5"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_5.geometry}
          material={materials['Material.004']}
          morphTargetDictionary={nodes.Cube058_5.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube058_5.morphTargetInfluences}
        />
        <mesh
          name="Cube058_6"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_6.geometry}
          material={materials['Material.007']}
          morphTargetDictionary={nodes.Cube058_6.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube058_6.morphTargetInfluences}
        />
      </group>
      <group
        position={[2.792, 3.045, -0.265]}
        rotation={[0.186, -0.028, -1.633]}
        scale={[0.014, 0.01, 0.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_2.geometry}
          material={materials['Material.006']}
        />
      </group>
      <group position={[2.845, 3.046, -0.262]} scale={[0.006, 0.006, 0.007]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <mesh
        name="Cube053"
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials['Material.019']}
        morphTargetDictionary={nodes.Cube053.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube053.morphTargetInfluences}
        position={[2.821, 3.048, -0.261]}
        scale={[0.016, 0.016, 0.019]}
      />
      <mesh
        name="Cube052"
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={materials['Material.018']}
        morphTargetDictionary={nodes.Cube052.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube052.morphTargetInfluences}
        position={[2.561, 3.052, -0.261]}
        scale={[0.016, 0.01, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={materials['Material.016']}
        position={[2.561, 3.051, -0.261]}
        scale={[0.011, 0.011, 0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube050.geometry}
        material={materials['Material.001']}
        position={[2.693, 2.751, -0.277]}
        rotation={[0, -1.571, 0]}
        scale={[-0.006, -0.005, -0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials['Material.001']}
        position={[2.694, 2.727, -0.273]}
        rotation={[0.228, -1.462, -0.033]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={materials['Material.001']}
        position={[2.694, 2.727, -0.273]}
        rotation={[1.351, -1.476, 1.062]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials['Material.001']}
        position={[2.693, 2.727, -0.273]}
        rotation={[1.923, -1.402, 1.634]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials['Material.001']}
        position={[2.694, 2.728, -0.269]}
        rotation={[1.619, -1.537, 1.597]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials['Material.001']}
        position={[2.693, 2.728, -0.269]}
        rotation={[1.601, -1.464, 1.579]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials['Material.001']}
        position={[2.952, 2.734, -0.264]}
        rotation={[1.453, -1.485, -1.533]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials['Material.001']}
        position={[2.95, 2.733, -0.263]}
        rotation={[2.404, -1.512, -0.594]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['Material.001']}
        position={[2.945, 2.729, -0.265]}
        rotation={[-1.917, -1.471, 1.298]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials['Material.001']}
        position={[2.951, 2.733, -0.267]}
        rotation={[-0.048, -1.537, -3.08]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.728, -0.268]}
        rotation={[-Math.PI / 2, -1.498, Math.PI / 2]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.732, -0.267]}
        rotation={[-1.837, -1.492, 1.395]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.728, -0.268]}
        rotation={[-Math.PI / 2, -1.424, Math.PI / 2]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials['Material.001']}
        position={[2.947, 2.733, -0.267]}
        rotation={[-1.992, -1.407, 1.26]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials['Material.001']}
        position={[2.95, 2.728, -0.268]}
        rotation={[-Math.PI / 2, -1.351, Math.PI / 2]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials['Material.001']}
        position={[2.95, 2.728, -0.269]}
        rotation={[-1.544, -1.391, 1.576]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.728, -0.269]}
        rotation={[-1.541, -1.464, 1.579]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.728, -0.269]}
        rotation={[-1.523, -1.537, 1.597]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.727, -0.273]}
        rotation={[-1.219, -1.402, 1.634]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.727, -0.273]}
        rotation={[-1.791, -1.476, 1.062]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.727, -0.273]}
        rotation={[-2.913, -1.462, -0.033]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials['Material.001']}
        position={[2.692, 2.728, -0.269]}
        rotation={[1.597, -1.391, 1.576]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials['Material.001']}
        position={[2.693, 2.728, -0.268]}
        rotation={[Math.PI / 2, -1.351, Math.PI / 2]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials['Material.001']}
        position={[2.695, 2.733, -0.267]}
        rotation={[1.149, -1.407, 1.26]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials['Material.001']}
        position={[2.694, 2.728, -0.268]}
        rotation={[Math.PI / 2, -1.424, Math.PI / 2]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials['Material.001']}
        position={[2.694, 2.732, -0.267]}
        rotation={[1.305, -1.492, 1.395]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials['Material.001']}
        position={[2.694, 2.728, -0.268]}
        rotation={[Math.PI / 2, -1.498, Math.PI / 2]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials['Material.001']}
        position={[2.692, 2.733, -0.267]}
        rotation={[3.094, -1.537, -3.08]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials['Material.001']}
        position={[2.949, 2.751, -0.277]}
        rotation={[-Math.PI, -1.571, 0]}
        scale={[0.006, 0.005, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials['Material.001']}
        position={[2.697, 2.729, -0.265]}
        rotation={[1.224, -1.471, 1.298]}
        scale={-0.006}
      />
      <group
        position={[2.644, 2.568, -0.27]}
        rotation={[0, 0, -0.002]}
        scale={[0.009, 0.012, 0.028]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_3.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_4.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials['Material.001']}
        position={[2.693, 2.733, -0.263]}
        rotation={[-0.738, -1.512, -0.594]}
        scale={-0.006}
      />
      <group
        position={[2.929, 2.995, -0.292]}
        rotation={[1.154, -1.421, 1.147]}
        scale={[0.025, 0.029, 0.026]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_3.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_4.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_5.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['Material.001']}
        position={[2.691, 2.734, -0.264]}
        rotation={[-1.688, -1.485, -1.533]}
        scale={-0.006}
      />
      <group
        position={[2.937, 2.92, -0.296]}
        rotation={[Math.PI, 0, -0.041]}
        scale={[-0.03, -0.03, -0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_4.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_5.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_6.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group
        position={[2.884, 2.639, -0.27]}
        rotation={[0, 0, -0.002]}
        scale={[0.007, 0.008, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
      </group>
      <group
        position={[2.859, 2.859, -0.234]}
        rotation={[0, 0.236, 0.046]}
        scale={[0.038, 0.051, 0.051]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_2.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group position={[2.823, 2.834, -0.252]} scale={[0.018, 0.015, 0.015]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials['BRAKE_Disk.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials['Material.003']}
        position={[2.864, 2.85, -0.262]}
        rotation={[0, 0, 0.27]}
        scale={[0.014, 0.012, 0.015]}
      />
      <group position={[2.823, 2.857, -0.26]} scale={[0.009, 0.007, 0.009]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials['BRAKE_Disk.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_2.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_3.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Material.006']}
        position={[2.821, 2.871, -0.262]}
        scale={0.025}
      />
      <group
        position={[2.865, 2.805, -0.264]}
        rotation={[0, 0, 0.178]}
        scale={[0.036, 0.031, 0.036]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_1.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_2.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_4.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_5.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_6.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group
        position={[2.773, 2.767, -0.264]}
        rotation={[0, 0, 0.178]}
        scale={[0.036, 0.031, 0.039]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials['BRAKE_Disk.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_4.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_5.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_6.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.003']}
        position={[2.822, 2.866, -0.242]}
        rotation={[1.693, 0, Math.PI]}
        scale={0.006}
      />
      <group
        position={[2.821, 2.957, -0.227]}
        rotation={[-0.251, 0, 0]}
        scale={[0.008, 0.011, 0.004]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group
        position={[2.859, 2.938, -0.318]}
        rotation={[-0.264, -0.516, -0.239]}
        scale={[0.021, 0.021, 0.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_2.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.003']}
        position={[2.822, 3.011, -0.3]}
        rotation={[2.823, 0, Math.PI]}
        scale={[0.007, 0.006, 0.006]}
      />
      <group position={[2.821, 3.035, -0.26]} scale={[0.016, 0.016, 0.019]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_2.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_3.geometry}
          material={materials['Material.015']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.002']}
        position={[2.823, 2.988, -0.243]}
        rotation={[0.452, 0, 0]}
        scale={0.004}
      />
      <group position={[2.822, 2.915, -0.236]} scale={0.027}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060.geometry}
        material={materials['BRAKE_Disk.002']}
        position={[2.822, 2.944, -0.205]}
        scale={0.009}
      />
      <group position={[2.813, 1.983, -0.174]} scale={[0.289, 0.179, 0.205]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['Material.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials['Material.028']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_3.geometry}
          material={materials['Material.029']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_4.geometry}
          material={materials['Material.030']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_5.geometry}
          material={materials['Material.031']}
        />
      </group>
      <group position={[3.673, 4.621, -0.144]} scale={[0.289, 0.179, 0.205]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials['Material.032']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_2.geometry}
          material={materials['Material.033']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_3.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_4.geometry}
          material={materials['Material.035']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_5.geometry}
          material={materials['Material.036']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/shelf.glb')



